apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetable
  labels:
    testing.upbound.io/example-name: demo
  name: demo
spec:
  forProvider:
    description: a custom route table demo
    name: demo
    route:
    - destination: 172.16.0.0/16
      nexthop: 967dc509-8224-4e0b-96c9-a565663f810c
      type: peering
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc-1
