apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: TrafficMirrorSession
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/trafficmirrorsession
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: Traffic mirror session created by terraform
    name: the_traffic_mirror_session_name
    priority: 10
    trafficMirrorFilterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    trafficMirrorSources:
    - source_port
    trafficMirrorTargetId: target_port
    trafficMirrorTargetType: eni
