apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: Vip
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vip
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vip
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}
