apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: MySQLAccount
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/mysqlaccount
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    name: test
    passwordSecretRef:
      key: password
      name: user-password
      namespace: crossplane-system
