apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: MySQLDatabasePrivilege
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/mysqldatabaseprivilege
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    dbName: test
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    users:
    - name: test
      readonly: false
