apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: PgAccountPrivileges
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/pgaccountprivileges
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    rolePrivileges:
    - CREATEROLE
    - LOGIN
    - REPLICATION
    systemRolePrivileges:
    - pg_signal_backend
    - root
    userName: test_account_name
