apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: PgPlugin
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/pgplugin
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    databaseName: test
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    name: pgaudit
