apiVersion: ecs.huaweicloud.crossplane.io/v1alpha1
kind: AutoLaunchGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/autolaunchgroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    launchTemplateId: ${var.launch_template_id}
    launchTemplateVersion: ${var.launch_template_version}
    name: ${var.auto_launch_group_name}
    overrides:
    - availabilityZone: ${var.availability_zone}
      flavorId: ${var.flavor_id}
    stableCapacity: 2
    targetCapacity: 2
