apiVersion: ecs.huaweicloud.crossplane.io/v1alpha1
kind: AutoLaunchGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/autolaunchgroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    launchTemplateId: the_launch_template_id
    launchTemplateVersion: the_launch_template_version
    name: the_auto_launch_group_name
    overrides:
    - availabilityZone: the_availability_zone
      flavorId: the_flavor_id
    stableCapacity: 2
    targetCapacity: 2
