apiVersion: ecs.huaweicloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    availabilityZone: cn-north-4a
    flavorId: c7.large.2
    imageId: 89ac6e18-d938-4b0d-b038-bcdb03a1b87f
    name: basic
    network:
    - uuid: 534b6d1b-b532-4e32-9e98-1329562a8f4e
    securityGroupIds:
    - 07d8d2fa-c206-4794-8804-8de5b22fb0cc
