apiVersion: smn.huaweicloud.crossplane.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: subscription_1
  name: subscription-1
spec:
  forProvider:
    endpoint: mailtest@gmail.com
    protocol: email
    remark: O&M
    topicUrnSelector:
      matchLabels:
        testing.upbound.io/example-name: topic_1
