apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: DatabaseLogsShrinking
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/databaselogsshrinking
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    dbName: ${var.db_name}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
