apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: ExtendLogLink
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/extendloglink
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    fileName: ${var.file_name}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
