apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: InstanceEIPAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/instanceeipassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceId: ${var.instance_id}
    publicIp: ${var.public_ip}
    publicIpId: ${var.node_id}
