apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: MySQLDatabasePrivilege
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/mysqldatabaseprivilege
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    dbName: ${var.db_name}
    instanceId: ${var.instance_id}
    users:
    - name: ${var.user_name_1}
      readonly: true
    - name: ${var.user_name_2}
      readonly: false
