apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: PgPluginParameter
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/pgpluginparameter
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceId: ${var.instance_id}
    name: shared_preload_libraries
    values:
    - pg_stat_kcache
