apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: Restore
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/restore
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backupId: ${var.backup_id}
    sourceInstanceId: ${var.source_instance_id}
    targetInstanceId: ${var.target_instance_id}
    type: backup
