apiVersion: rds.huaweicloud.crossplane.io/v1alpha1
kind: SQLAudit
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1alpha1/sqlaudit
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceId: ${var.instance_id}
    keepDays: 5
