apiVersion: dcs.huaweicloud.crossplane.io/v1alpha1
kind: BigkeyAnalysis
metadata:
  annotations:
    meta.upbound.io/example-id: dcs/v1alpha1/bigkeyanalysis
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
