apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: VpcEipAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/vpceipassociate
  labels:
    testing.upbound.io/example-name: associated
  name: associated
spec:
  initProvider:
    portId: ""
  forProvider:
    fixedIp: 192.168.0.202
    networkId: 238f627c-1346-448b-924c-9a788793c85b
    publicIp: 113.44.161.78
