apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RabbitmqExchangeAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rabbitmqexchangeassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    destination: test-queue
    destinationType: Queue
    exchange: test-exchange
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    routingKey: test123
    vhost: test-host
