apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RabbitmqQueue
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rabbitmqqueue
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    autoDelete: false
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    name: test-queue
    vhost: test-host
