apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RabbitmqQueueMessageClear
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rabbitmqqueuemessageclear
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    queue: test-queue
    vhost: test-host
