apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RocketmqInstance
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rocketmqinstance
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    availabilityZones:
      - cn-north-4a
    brokerNum: 1
    description: this is a rocketmq instance
    engineVersion: 4.8.0
    flavorId: c6.4u8g.cluster
    name: rocketmq_name_test
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: secgroup
    storageSpace: 300
    storageSpecCode: dms.physical.storage.high.v2
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc
