apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RocketmqConsumerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rocketmqconsumergroup
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    broadcast: true
    brokers:
    - broker-0
    description: the description of the consumer group
    enabled: true
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    name: consumer_group_test
    retryMaxTimes: 3
