apiVersion: obs.huaweicloud.crossplane.io/v1alpha1
kind: BucketReplication
metadata:
  annotations:
    meta.upbound.io/example-id: obs/v1alpha1/bucketreplication
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    agency: ${var.agency}
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    destinationBucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
