apiVersion: ces.huaweicloud.crossplane.io/v1alpha1
kind: EventReport
metadata:
  annotations:
    meta.upbound.io/example-id: ces/v1alpha1/eventreport
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    detail:
    - content: the_content
      level: Major
      resourceId: the_resource_id
      resourceName: the_resource_name
      state: normal
      user: the_user
    name: the_name
    source: the_source
    time: the_time
