apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: Eipv3Associate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/eipv3associate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    associateInstanceId: ${var.elb_id}
    associateInstanceType: ELB
    publicipIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
