apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: GlobalInternetBandwidth
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/globalinternetbandwidth
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessSite: ${data.huaweicloud_global_eip_pools.all.geip_pools[0].access_site}
    chargeMode: 95peak_guar
    enterpriseProjectId: ${var.enterprise_project_id}
    isp: ${data.huaweicloud_global_eip_pools.all.geip_pools[0].isp}
    name: ${var.bandwidth_name}
    size: 300
    tags:
      foo: bar
      key: value
    type: ${data.huaweicloud_global_eip_pools.all.geip_pools[0].allowed_bandwidth_types[0].type}
