apiVersion: eip.huaweicloud.crossplane.io/v1alpha1
kind: VpcEipAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: eip/v1alpha1/vpceipassociate
  labels:
    testing.upbound.io/example-name: associated
  name: associated
spec:
  forProvider:
    fixedIp: 192.168.0.100
    networkId: ${var.network_id}
    publicIp: ${var.public_address}
