apiVersion: nat.huaweicloud.crossplane.io/v1alpha1
kind: PrivateSnatRule
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1alpha1/privatesnatrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  initProvider:
    cidr: ""
  forProvider:
    gatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test-private
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet1
    transitIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
