apiVersion: nat.huaweicloud.crossplane.io/v1alpha1
kind: PrivateTransitIP
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1alpha1/privatetransitip
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    enterpriseProjectId: "0"
    ipAddress: 192.168.0.100
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet1
    tags:
      foo: bar

---

apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnet
  labels:
    testing.upbound.io/example-name: subnet1
  name: subnet1
spec:
  forProvider:
    availabilityZone: cn-north-4a
    cidr: 192.168.0.0/24
    gatewayIp: 192.168.0.1
    name: crossplane_test1
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc1

---

apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpc
  labels:
    testing.upbound.io/example-name: vpc1
  name: vpc1
spec:
  forProvider:
    cidr: 192.168.0.0/16
    name: crossplane_test1