apiVersion: swr.huaweicloud.crossplane.io/v1alpha1
kind: ImageRetentionPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: swr/v1alpha1/imageretentionpolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    number: 20
    organization: ${var.organization_name}
    repository: ${var.repository_name}
    tagSelectors:
    - kind: label
      pattern: abc
    - kind: regexp
      pattern: abc*
    type: date_rule
