apiVersion: swr.huaweicloud.crossplane.io/v1alpha1
kind: ImagePermissions
metadata:
  annotations:
    meta.upbound.io/example-id: swr/v1alpha1/imagepermissions
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    organization: ${var.organization_name}
    repository: ${var.repository_name}
    users:
    - permission: Manage
      userIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      userName: test_user1
    - permission: Read
      userIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
