apiVersion: smn.huaweicloud.crossplane.io/v1alpha1
kind: MessagePublish
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1alpha1/messagepublish
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    message: test
    subject: ${var.subject}
    topicUrnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
