apiVersion: smn.huaweicloud.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: smn/v1alpha1/topic
  labels:
    testing.upbound.io/example-name: topic_1
  name: topic-1
spec:
  forProvider:
    displayName: The display name of topic_1
    name: topic_1
