apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RabbitmqExchangeAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rabbitmqexchangeassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    destination: ${var.destination}
    destinationType: Queue
    exchange: ${var.exchange}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    routingKey: ${var.routing_key}
    vhost: ${var.vhost}
