apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RabbitmqUser
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rabbitmquser
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessKey: ${var.user_name}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    vhosts:
    - conf: .*
      read: .*
      vhost: default
      write: .*
