apiVersion: dms.huaweicloud.crossplane.io/v1alpha1
kind: RabbitmqVhost
metadata:
  annotations:
    meta.upbound.io/example-id: dms/v1alpha1/rabbitmqvhost
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: ${var.name}
