apiVersion: nat.huaweicloud.crossplane.io/v1alpha1
kind: DnatRule
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1alpha1/dnatrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    externalServicePort: 8023
    floatingIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    internalServicePort: 23
    natGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    portId: ${huaweicloud_compute_instance.test.network[0].port}
    protocol: tcp

---

apiVersion: ecs.huaweicloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1alpha1/dnatrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider: {}
