apiVersion: nat.huaweicloud.crossplane.io/v1alpha1
kind: SnatRule
metadata:
  annotations:
    meta.upbound.io/example-id: nat/v1alpha1/snatrule
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    floatingIpIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    natGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
