apiVersion: cc.huaweicloud.crossplane.io/v1alpha1
kind: BandwidthPackage
metadata:
  annotations:
    meta.upbound.io/example-id: cc/v1alpha1/bandwidthpackage
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    bandwidth: 5
    billingMode: 3
    chargeMode: bandwidth
    description: This is a demo
    localAreaId: Chinese-Mainland
    name: demo
    remoteAreaId: Chinese-Mainland
    tags:
      foo: bar
      key: value
