apiVersion: cc.huaweicloud.crossplane.io/v1alpha1
kind: CentralNetworkAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: cc/v1alpha1/centralnetworkattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    centralNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: This is a demo
    enterpriseRouterId: ${var.enterprise_router_id}
    enterpriseRouterProjectId: ${var.enterprise_router_project_id}
    enterpriseRouterRegionId: ${var.enterprise_router_region_id}
    globalDcGatewayId: ${var.global_dc_gateway_id}
    globalDcGatewayProjectId: ${var.global_dc_gateway_project_id}
    globalDcGatewayRegionId: ${var.global_dc_gateway_region_id}
    name: demo
