apiVersion: cc.huaweicloud.crossplane.io/v1alpha1
kind: GlobalConnectionBandwidthAssociate
metadata:
  annotations:
    meta.upbound.io/example-id: cc/v1alpha1/globalconnectionbandwidthassociate
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    gcbBindingResources:
    - projectId: ${var.project_id}
      regionId: global
      resourceId: ${var.resource_id}
      resourceType: GEIP
    gcbIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
