apiVersion: cc.huaweicloud.crossplane.io/v1alpha1
kind: NetworkInstance
metadata:
  annotations:
    meta.upbound.io/example-id: cc/v1alpha1/networkinstance
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    cidrs:
    - ${var.cidr}
    cloudConnectionId: ${var.cloud_connection_id}
    instanceId: ${var.vpc_instance_id}
    projectId: ${var.vpc_project_id}
    regionId: ${var.vpc_region_id}
    type: vpc
