apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: FlowLog
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/flowlog
  labels:
    testing.upbound.io/example-name: test_flowlog
  name: test-flowlog
spec:
  forProvider:
    logGroupId: ${huaweicloud_lts_group.test_group.id}
    logStreamId: ${huaweicloud_lts_stream.test_stream.id}
    name: flowlog-test
    resourceId: ${var.subnet_id}
    resourceType: network
    trafficType: all
