apiVersion: vpc.huaweicloud.crossplane.io/v1alpha1
kind: SubNetworkInterface
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/subnetworkinterface
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: create a supplementary network interface
    parentId: ${var.parent_id}
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vlanId: ${var.vlan_id}
